language: python
python: 2.7
sudo: false

# note: python3.5 is not preinstalled on docker-based (i.e. sudo: false)
#       Travis workers at the moment of this writing, so we need to get
#       it via addon repository.
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5
      - python3.5-dev
      - python3.6
      - python3.6-dev
      - python3.7
      - python3.7-dev

env:
  - TOX_ENV=py27-django15
  - TOX_ENV=py27-django16
  - TOX_ENV=py27-django17
  - TOX_ENV=py27-django18
  - TOX_ENV=py27-django19

  - TOX_ENV=py35-django18
  - TOX_ENV=py35-django19

  - TOX_ENV=py36-django18
  - TOX_ENV=py36-django19

  - TOX_ENV=py37-django18
  - TOX_ENV=py37-django19

  - TOX_ENV=coverage
install:
  - pip install -U tox pip
script:
  - tox -e $TOX_ENV
